# Nombre del Workflow
name: CI

# Evento que dispara el workflow (ej. al hacer un push)
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

# Trabajos a ejecutar
jobs:
  # Nombre del único trabajo
  build:
    # Máquina virtual donde se ejecutará
    runs-on: ubuntu-latest

    # Pasos que se realizarán en el trabajo
    steps:
      # Un paso simple que imprime un mensaje
      - run: echo "Hola Mundo! Este es mi primer log."
      - run: echo "Este paso también generará un log."
